soc: qcom: rpmh-rsc: add missing header
* gcc complains:

    CC      drivers/soc/qcom/rpmh-rsc.o
    drivers/soc/qcom/rpmh-rsc.c:933:16: error: expected declaration specifiers or '...' before string constant
    933 | MODULE_LICENSE("GPL v2");
        |                ^~~~~~~~
    drivers/soc/qcom/rpmh-rsc.c:934:20: error: expected declaration specifiers or '...' before string constant
    934 | MODULE_DESCRIPTION("Qualcomm RPM-Hardened (RPMH) Communication driver");
        |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC      drivers/soc/qcom/secure_buffer.o
    CC      drivers/soc/qcom/scm.o
    make[3]: *** [scripts/Makefile.build:339: drivers/soc/qcom/rpmh-rsc.o] Error 1
    make[3]: *** Waiting for unfinished jobs....

Change-Id: Ib49a7907eb3b39f1ff3e9f670a45bbcade56dd28